services:
  aftekenen:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: ["yarn", "workspace", "aftekenen", "serve:https"]